theme: jekyll-theme-minimal
title: Nikos Triantafyllou's homepage
description: Personal webpage


# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: cyborg # paper cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti
