# config.yml

# Site settings
title: "Nikos Triantafyllou"
description: "Website"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nikos-triantafyllou.github.io" # the base hostname & protocol for your site

# Theme settings
theme: "bootstrap"
bootstrap_theme: "cyborg" # Specify the Bootswatch theme here

# Plugins
plugins:
  - jekyll-feed # Example of a plugin, add any others you need
  - jekyll-sitemap

# Include additional CSS or JS files
include:
  - assets/css # Ensure this includes your CSS assets folder if using custom styles

# Custom settings for Bootstrap and Bootswatch
bootstrap_css: "https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.0/cyborg/bootstrap.min.css"
bootstrap_js: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"

# Build settings
markdown: kramdown
highlighter: rouge

# Add any additional configuration settings here
paginate: 5 # Example: items per page if using pagination
permalink: /:categories/:title/

